[workspace]
resolver = "2"
members = [
    "contracts/bazaar_deal_engine",
    "contracts/demand_circle_registry",
    "crates/bazaar_indexer",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
authors = ["KingTaiwoDev"]
license = "MIT"
repository = "https://github.com/Stellar-Bazaar/stellar-bazaar-core"

[profile.release]
opt-level = "z"
overflow-checks = true
